eureka:
  client:
    serviceUrl:
      defaultZone: http://10.88.113.67:8761/eureka     
debug: true
logging:                               
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.richfit.mapper: debug
  